include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - await_only_futures
    - avoid_returning_null_for_void
    - cancel_subscriptions
    - directives_ordering
    - flutter_style_todos
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - sort_pub_dependencies
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_getters_setters
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps
    - void_checks
    # - always_put_required_named_parameters_first # we prefer having parameters in the same order as fields https://github.com/flutter/flutter/issues/10219
    - always_require_non_null_named_parameters
    - always_specify_types
    - annotate_overrides
    - prefer_single_quotes
    - prefer_generic_function_type_aliases
    - prefer_final_fields

analyzer:
  errors:
    constant_identifier_names: ignore
    always_put_control_body_on_new_line: ignore
    argument_type_not_assignable: ignore
    omit_local_variable_types: ignore
    slash_for_doc_comments: ignore
    library_prefixes: ignore
    unused_field: ignore
    avoid_init_to_null: ignore
    prefer_is_empty: ignore
    unused_element: ignore
    curly_braces_in_flow_control_structures: ignore
    unnecessary_null_in_if_null_operators: ignore
    prefer_contains: ignore
    avoid_types_as_parameter_names: ignore
    empty_catches: ignore
    unawaited_futures: ignore
    use_rethrow_when_possible: ignore
    unused_import: ignore
    must_be_immutable: ignore
    todo: ignore
    non_constant_identifier_names: ignore
    unnecessary_null_comparison: ignore

  exclude:
    - lib/src/grammar_parser.dart
    - tool/*